(()=>{"use strict";
const KEY="dhm_complete_v2";
const pages=[
 ["dashboard","Dashboard","fa-gauge-high"],["students","Students","fa-user-graduate"],["fees","Fees","fa-money-bill-wave"],["income","Income","fa-arrow-trend-up"],["expense","Expense","fa-arrow-trend-down"],["accounts","Accounts","fa-calculator"],["attendance","Attendance","fa-calendar-check"],["results","Exam & Results","fa-graduation-cap"],["staff","Teachers & Staff","fa-chalkboard-user"],["salary","Salary","fa-wallet"],["hostel","Food / Hostel","fa-bed"],["donors","Donors / Donations","fa-hand-holding-heart"],["notices","Notices","fa-bullhorn"],["reports","Reports","fa-chart-pie"],["settings","Settings","fa-gear"]
];
const defaults={settings:{name:"ডিঙ্গেল হাফিজিয়া মাদ্রাসা",english:"Dingel Hafizia Madrasa",address:"Dingel, West Bengal, India",phone:"",email:"",fee:500,academic:"2026-27",currency:"INR"},
students:[],fees:[],income:[],expense:[],attendance:[],results:[],staff:[],salary:[],hostel:[],donors:[],notices:[],transfers:[],activity:[]};
let S=load(), page="dashboard", filter="";
let fb=null,auth=null,user=null;
function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function toast(m,bad=false){let x=document.createElement("div");x.className="toast "+(bad?"bad":"");x.innerHTML=`<i class="fa-solid ${bad?"fa-circle-exclamation":"fa-circle-check"}"></i>${MU.esc(m)}`;MU.q("#toast").appendChild(x);setTimeout(()=>x.remove(),2800)}
function activeStudents(){return S.students.filter(x=>x.status!=="inactive")}
function calc(){
 let m=MU.month(), fs=S.fees.filter(x=>x.month===m), inc=S.income.filter(x=>x.date?.slice(0,7)===m), ex=S.expense.filter(x=>x.date?.slice(0,7)===m);
 let expected=activeStudents().filter(x=>x.type!=="orphan").reduce((a,x)=>a+Number(x.fee||0),0);
 let paid=fs.reduce((a,x)=>a+Number(x.paid||0),0), oi=inc.reduce((a,x)=>a+Number(x.amount||0),0), eo=ex.reduce((a,x)=>a+Number(x.amount||0),0);
 return {students:activeStudents().length,orphans:activeStudents().filter(x=>x.type==="orphan").length,expected,paid,due:Math.max(0,expected-paid),oi,eo,balance:paid+oi-eo}
}
function initFirebase(){let c=window.FIREBASE_CONFIG||{};if(!c.apiKey||c.apiKey.startsWith("PASTE_"))return;try{if(!firebase.apps.length)firebase.initializeApp(c);fb=firebase.firestore();auth=firebase.auth();auth.onAuthStateChanged(u=>{user=u;MU.q("#cloudState").textContent=u?"Firebase synced":"Local / Offline";if(u)syncDown()})}catch(e){console.warn(e)}}
async function syncDown(){try{let d=await fb.collection("madrasa").doc("main").get();if(d.exists){S=Object.assign({},defaults,d.data());save();render()}else await syncUp()}catch(e){toast("Cloud sync failed; local data kept",true)}}
async function syncUp(){save();if(fb&&user)try{await fb.collection("madrasa").doc("main").set(S);MU.q("#cloudState").textContent="Firebase synced"}catch(e){}}
async function persist(){save();await syncUp();render()}
function nav(){MU.q("#nav").innerHTML=pages.map(p=>`<button class="navbtn ${page===p[0]?"active":""}" data-page="${p[0]}"><i class="fa-solid ${p[2]}"></i><span>${p[1]}</span></button>`).join("")}
function render(){nav();MU.q("#brandName").textContent=S.settings.name;MU.q("#pageTitle").textContent=pages.find(x=>x[0]===page)?.[1]||page;MU.q("#dateText").textContent=new Date().toLocaleDateString("bn-BD",{weekday:"long",day:"numeric",month:"long",year:"numeric"});let f=views[page]||views.dashboard;MU.q("#view").innerHTML=f();bind()}
const stat=(ic,l,v)=>`<div class="stat"><div class="staticon"><i class="fa-solid ${ic}"></i></div><div><small>${l}</small><strong>${v}</strong></div></div>`;
const head=(title,sub,action,label)=>`<div class="head"><div><h1>${title}</h1><p>${sub}</p></div>${action?`<button class="btn primary" data-act="${action}"><i class="fa-solid fa-plus"></i>${label}</button>`:""}</div>`;
const empty=t=>`<div class="empty"><i class="fa-regular fa-folder-open"></i><p>${t}</p></div>`;
function dashboard(){let c=calc(),tx=[...S.fees.map(x=>({...x,t:"Fee",amt:x.paid})),...S.income.map(x=>({...x,t:"Income",amt:x.amount})),...S.expense.map(x=>({...x,t:"Expense",amt:-x.amount}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,8);return `
<div class="hero"><div><span>MANAGEMENT OVERVIEW</span><h1>আসসালামু আলাইকুম 👋</h1><p>মাদ্রাসার ছাত্র, ফি ও আর্থিক হিসাব এক জায়গায় পরিচালনা করুন।</p></div><button class="btn light" data-act="student"><i class="fa-solid fa-user-plus"></i> নতুন ভর্তি</button></div>
<div class="stats">${stat("fa-user-graduate","মোট ছাত্র",c.students)}${stat("fa-child-reaching","এতিম",c.orphans)}${stat("fa-money-bill-wave","ফি আদায়",MU.money(c.paid))}${stat("fa-triangle-exclamation","বকেয়া",MU.money(c.due))}${stat("fa-arrow-trend-up","আয়",MU.money(c.oi))}${stat("fa-arrow-trend-down","খরচ",MU.money(c.eo))}${stat("fa-wallet","ব্যালেন্স",MU.money(c.balance))}</div>
<div class="grid2"><div class="card"><div class="cardhead"><b>Quick Actions</b></div><div class="quick">${[["student","fa-user-plus","Student Admission"],["fee","fa-receipt","Collect Fee"],["income","fa-plus","Add Income"],["expense","fa-minus","Add Expense"],["attendance","fa-calendar-check","Attendance"],["report","fa-print","Print Report"]].map(x=>`<button data-act="${x[0]}"><i class="fa-solid ${x[1]}"></i>${x[2]}</button>`).join("")}</div></div>
<div class="card"><div class="cardhead"><b>This Month</b><span class="tag">${MU.month()}</span></div><div class="summary"><div><span>Expected Fee</span><b>${MU.money(c.expected)}</b></div><div><span>Collected</span><b class="green">${MU.money(c.paid)}</b></div><div><span>Due</span><b class="red">${MU.money(c.due)}</b></div><div><span>Net Balance</span><b>${MU.money(c.balance)}</b></div></div></div></div>
<div class="card"><div class="cardhead"><b>Recent Transactions</b><button class="link" data-page="reports">View Reports</button></div><div class="tablewrap"><table><thead><tr><th>Date</th><th>Type</th><th>Description</th><th>Amount</th></tr></thead><tbody>${tx.length?tx.map(x=>`<tr><td>${MU.date(x.date)}</td><td><span class="tag">${x.t}</span></td><td>${MU.esc(x.studentName||x.category||x.description||"—")}</td><td class="${x.amt<0?"red":"green"}">${MU.money(x.amt)}</td></tr>`).join(""):`<tr><td colspan="4">${empty("No transactions yet")}</td></tr>`}</tbody></table></div></div>`}
function students(){let a=S.students.filter(x=>`${x.name} ${x.roll} ${x.phone} ${x.className}`.toLowerCase().includes(filter.toLowerCase()));return head("Student Management","Admission, profile, fees, status and records.","student","Add Student")+`<div class="toolbar"><input id="filter" value="${MU.esc(filter)}" placeholder="🔍 Search name, roll, phone, class..."><select id="typefilter"><option value="">All Types</option><option value="general">General</option><option value="orphan">Orphan / এতিম</option></select></div><div class="card tablewrap"><table><thead><tr><th>ID/Roll</th><th>Student</th><th>Class</th><th>Type</th><th>Fee</th><th>Phone</th><th>Status</th><th>Action</th></tr></thead><tbody>${a.length?a.map(s=>`<tr><td><b>${MU.esc(s.roll||"—")}</b></td><td><div class="person"><div class="mini">${MU.esc((s.name||"?")[0])}</div><div><b>${MU.esc(s.name)}</b><small>${MU.esc(s.father||"")}</small></div></div></td><td>${MU.esc(s.className)}</td><td><span class="tag ${s.type==="orphan"?"warn":""}">${s.type==="orphan"?"Orphan / এতিম":"General"}</span></td><td>${MU.money(s.type==="orphan"?0:s.fee)}</td><td>${MU.esc(s.phone||"—")}</td><td><span class="status">${s.status}</span></td><td><button class="iconbtn sm" data-edit="${s.id}"><i class="fa-solid fa-pen"></i></button><button class="iconbtn sm red" data-delstudent="${s.id}"><i class="fa-solid fa-trash"></i></button></td></tr>`).join(""):`<tr><td colspan="8">${empty("No students found")}</td></tr>`}</tbody></table></div>`}
function fees(){let a=S.fees.filter(x=>`${x.studentName} ${x.roll} ${x.month}`.toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>String(b.date).localeCompare(String(a.date)));let tot=a.reduce((n,x)=>n+Number(x.paid||0),0);return head("Fees Management","Monthly collection, due, history and receipts.","fee","Collect Fee")+`<div class="mini"><div>Records <b>${a.length}</b></div><div>Collected <b>${MU.money(tot)}</b></div><div>This Month <b>${MU.money(calc().paid)}</b></div><div>Total Due <b>${MU.money(calc().due)}</b></div></div><div class="toolbar"><input id="filter" value="${MU.esc(filter)}" placeholder="Search student..."></div><div class="card tablewrap"><table><thead><tr><th>Date</th><th>Student</th><th>Month</th><th>Expected</th><th>Paid</th><th>Due</th><th>Method</th><th>Receipt</th></tr></thead><tbody>${a.length?a.map(f=>`<tr><td>${MU.date(f.date)}</td><td><b>${MU.esc(f.studentName)}</b><small>Roll ${MU.esc(f.roll)}</small></td><td>${f.month}</td><td>${MU.money(f.expected)}</td><td class="green">${MU.money(f.paid)}</td><td class="red">${MU.money(f.due)}</td><td>${MU.esc(f.method)}</td><td><button class="iconbtn sm" data-receipt="${f.id}"><i class="fa-solid fa-print"></i></button></td></tr>`).join(""):`<tr><td colspan="8">${empty("No fee records")}</td></tr>`}</tbody></table></div>`}
function ledger(kind){let arr=S[kind],income=kind==="income";let total=arr.reduce((n,x)=>n+Number(x.amount||0),0);return head(income?"Income Management":"Expense Management",income?"Donation and other income":"All madrasa expenses",kind, income?"Add Income":"Add Expense")+`<div class="mini"><div>Total Records <b>${arr.length}</b></div><div>Total <b>${MU.money(total)}</b></div><div>This Month <b>${MU.money(arr.filter(x=>x.date?.slice(0,7)===MU.month()).reduce((n,x)=>n+Number(x.amount||0),0))}</b></div></div><div class="card tablewrap"><table><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Method</th><th>Amount</th><th></th></tr></thead><tbody>${arr.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(x=>`<tr><td>${MU.date(x.date)}</td><td><span class="tag">${MU.esc(x.category)}</span></td><td>${MU.esc(x.description)}</td><td>${MU.esc(x.method)}</td><td class="${income?"green":"red"}">${MU.money(x.amount)}</td><td><button class="iconbtn sm red" data-delledger="${kind}:${x.id}"><i class="fa-solid fa-trash"></i></button></td></tr>`).join("")||`<tr><td colspan="6">${empty("No records")}</td></tr>`}</tbody></table></div>`}
function accounts(){let months=[...new Set([...S.fees.map(x=>x.month),...S.income.map(x=>x.date?.slice(0,7)),...S.expense.map(x=>x.date?.slice(0,7))])].filter(Boolean).sort().reverse();if(!months.includes(MU.month()))months.unshift(MU.month());return head("Monthly Accounts","Complete financial statement with income, expense and closing balance.","export","Backup")+`<div class="card tablewrap"><table><thead><tr><th>Month</th><th>Fee</th><th>Other Income</th><th>Total Income</th><th>Expense</th><th>Net Balance</th></tr></thead><tbody>${months.map(m=>{let f=S.fees.filter(x=>x.month===m).reduce((n,x)=>n+Number(x.paid||0),0),i=S.income.filter(x=>x.date?.slice(0,7)===m).reduce((n,x)=>n+Number(x.amount||0),0),e=S.expense.filter(x=>x.date?.slice(0,7)===m).reduce((n,x)=>n+Number(x.amount||0),0);return `<tr><td><b>${m}</b></td><td>${MU.money(f)}</td><td>${MU.money(i)}</td><td class="green">${MU.money(f+i)}</td><td class="red">${MU.money(e)}</td><td><b>${MU.money(f+i-e)}</b></td></tr>`}).join("")}</tbody></table></div>`}
function attendance(){let m=MU.month(), students=activeStudents();return head("Attendance","Daily attendance register and monthly summary.","attendanceSave","Save Attendance")+`<div class="toolbar"><input id="attDate" type="date" value="${MU.today()}"><select id="attClass"><option value="">All Classes</option>${[...new Set(students.map(x=>x.className))].map(c=>`<option>${MU.esc(c)}</option>`).join("")}</select></div><div class="card tablewrap"><table><thead><tr><th>Roll</th><th>Student</th><th>Class</th><th>Status</th></tr></thead><tbody>${students.map(s=>{let r=S.attendance.find(x=>x.date===MU.q("#attDate")?.value&&x.studentId===s.id);return `<tr><td>${MU.esc(s.roll)}</td><td>${MU.esc(s.name)}</td><td>${MU.esc(s.className)}</td><td><select class="att" data-att="${s.id}"><option ${r?.status==="Present"?"selected":""}>Present</option><option ${r?.status==="Absent"?"selected":""}>Absent</option><option ${r?.status==="Leave"?"selected":""}>Leave</option></select></td></tr>`}).join("")||`<tr><td colspan="4">${empty("Add students first")}</td></tr>`}</tbody></table></div>`}
function results(){return head("Exam & Results","Exam records and student performance.","result","Add Result")+`<div class="card tablewrap"><table><thead><tr><th>Date</th><th>Student</th><th>Exam</th><th>Subject</th><th>Marks</th><th>Grade</th><th></th></tr></thead><tbody>${S.results.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(x=>`<tr><td>${MU.date(x.date)}</td><td>${MU.esc(x.studentName)}</td><td>${MU.esc(x.exam)}</td><td>${MU.esc(x.subject)}</td><td>${x.marks}/${x.total}</td><td><span class="tag">${MU.esc(x.grade)}</span></td><td><button class="iconbtn sm red" data-delresult="${x.id}"><i class="fa-solid fa-trash"></i></button></td></tr>`).join("")||`<tr><td colspan="7">${empty("No result records")}</td></tr>`}</tbody></table></div>`}
function staff(){return head("Teachers & Staff","Teacher/staff profile and employment records.","staff","Add Staff")+`<div class="card tablewrap"><table><thead><tr><th>Name</th><th>Role</th><th>Phone</th><th>Join Date</th><th>Salary</th><th>Status</th><th></th></tr></thead><tbody>${S.staff.map(x=>`<tr><td><b>${MU.esc(x.name)}</b></td><td>${MU.esc(x.role)}</td><td>${MU.esc(x.phone)}</td><td>${MU.date(x.join)}</td><td>${MU.money(x.salary)}</td><td><span class="status">${x.status}</span></td><td><button class="iconbtn sm red" data-delstaff="${x.id}"><i class="fa-solid fa-trash"></i></button></td></tr>`).join("")||`<tr><td colspan="7">${empty("No staff records")}</td></tr>`}</tbody></table></div>`}
function salary(){return head("Salary Management","Staff salary payment history.","salary","Pay Salary")+`<div class="card tablewrap"><table><thead><tr><th>Date</th><th>Staff</th><th>Month</th><th>Salary</th><th>Paid</th><th>Method</th></tr></thead><tbody>${S.salary.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(x=>`<tr><td>${MU.date(x.date)}</td><td>${MU.esc(x.staffName)}</td><td>${x.month}</td><td>${MU.money(x.salary)}</td><td class="green">${MU.money(x.paid)}</td><td>${MU.esc(x.method)}</td></tr>`).join("")||`<tr><td colspan="6">${empty("No salary records")}</td></tr>`}</tbody></table></div>`}
function hostel(){return head("Food / Hostel","Boarding and food expense records.","hostel","Add Record")+`<div class="card tablewrap"><table><thead><tr><th>Date</th><th>Category</th><th>Students</th><th>Amount</th><th>Note</th></tr></thead><tbody>${S.hostel.map(x=>`<tr><td>${MU.date(x.date)}</td><td>${MU.esc(x.category)}</td><td>${x.students}</td><td class="red">${MU.money(x.amount)}</td><td>${MU.esc(x.note)}</td></tr>`).join("")||`<tr><td colspan="5">${empty("No hostel/food records")}</td></tr>`}</tbody></table></div>`}
function donors(){return head("Donors & Donations","Donor directory and donation history.","donor","Add Donation")+`<div class="card tablewrap"><table><thead><tr><th>Date</th><th>Donor</th><th>Phone</th><th>Purpose</th><th>Amount</th><th>Method</th></tr></thead><tbody>${S.donors.map(x=>`<tr><td>${MU.date(x.date)}</td><td><b>${MU.esc(x.name)}</b></td><td>${MU.esc(x.phone)}</td><td>${MU.esc(x.purpose)}</td><td class="green">${MU.money(x.amount)}</td><td>${MU.esc(x.method)}</td></tr>`).join("")||`<tr><td colspan="6">${empty("No donation records")}</td></tr>`}</tbody></table></div>`}
function notices(){return head("Notice Board","Publish important madrasa notices.","notice","New Notice")+`<div class="noticegrid">${S.notices.map(x=>`<article class="noticecard"><span>${MU.date(x.date)}</span><h3>${MU.esc(x.title)}</h3><p>${MU.esc(x.body)}</p><button class="iconbtn sm red" data-delnotice="${x.id}"><i class="fa-solid fa-trash"></i></button></article>`).join("")||empty("No notices")}</div>`}
function reports(){let c=calc();return head("Reports","Management summary, financial report and export.","report","Print Report")+`<div class="stats">${stat("fa-user-graduate","Students",c.students)}${stat("fa-money-bill-wave","Fees",MU.money(c.paid))}${stat("fa-arrow-trend-up","Income",MU.money(c.oi))}${stat("fa-arrow-trend-down","Expense",MU.money(c.eo))}${stat("fa-wallet","Balance",MU.money(c.balance))}${stat("fa-triangle-exclamation","Due",MU.money(c.due))}</div><div class="grid2"><div class="card"><div class="cardhead"><b>Student Categories</b></div><div class="summary"><div><span>General</span><b>${activeStudents().filter(x=>x.type!=="orphan").length}</b></div><div><span>Orphan / এতিম</span><b>${c.orphans}</b></div><div><span>Inactive</span><b>${S.students.filter(x=>x.status==="inactive").length}</b></div></div></div><div class="card"><div class="cardhead"><b>Data & Backup</b></div><div class="quick"><button data-act="export"><i class="fa-solid fa-download"></i> Export JSON</button><button data-act="import"><i class="fa-solid fa-upload"></i> Import JSON</button><button data-act="report"><i class="fa-solid fa-print"></i> Print A4 Report</button></div></div></div>`}
function settings(){let s=S.settings;return head("Madrasa Settings","Institution profile, defaults and data safety.","saveSettings","Save Settings")+`<div class="grid2"><div class="card form"><h3>Institution Profile</h3>${field("sn","Madrasa Name",s.name)}${field("se","English Name",s.english)}${field("sa","Address",s.address,"textarea")}${field("sp","Phone",s.phone)}${field("sm","Email",s.email)}</div><div class="card form"><h3>Academic & Fee</h3>${field("sf","Default Monthly Fee",s.fee,"number")}${field("sy","Academic Year",s.academic)}<label>Currency</label><select id="sc"><option ${s.currency==="INR"?"selected":""}>INR</option><option ${s.currency==="BDT"?"selected":""}>BDT</option></select><hr><button class="btn" data-act="export"><i class="fa-solid fa-download"></i> Full Backup</button><button class="btn danger-outline" data-act="reset">Reset Local Data</button></div></div>`}
const field=(id,l,v,t="text")=>t==="textarea"?`<label>${l}</label><textarea id="${id}">${MU.esc(v||"")}</textarea>`:`<label>${l}</label><input id="${id}" type="${t}" value="${MU.esc(v??"")}">`;
const views={dashboard,students,fees,income:()=>ledger("income"),expense:()=>ledger("expense"),accounts,attendance,results,staff,salary,hostel,donors,notices,reports,settings};
function bind(){
 document.querySelectorAll("[data-page]").forEach(x=>x.onclick=()=>{page=x.dataset.page;filter="";render()});
 document.querySelectorAll("[data-act]").forEach(x=>x.onclick=()=>act(x.dataset.act));
 let f=MU.q("#filter");if(f)f.oninput=e=>{filter=e.target.value;render();let q=MU.q("#filter");q?.focus();q?.setSelectionRange(filter.length,filter.length)};
 document.querySelectorAll("[data-edit]").forEach(x=>x.onclick=()=>studentModal(x.dataset.edit));
 document.querySelectorAll("[data-delstudent]").forEach(x=>x.onclick=()=>del("students",x.dataset.delstudent,"student"));
 document.querySelectorAll("[data-delledger]").forEach(x=>x.onclick=()=>{let [k,id]=x.dataset.delledger.split(":");del(k,id,"record")});
 document.querySelectorAll("[data-receipt]").forEach(x=>x.onclick=()=>receipt(x.dataset.receipt));
 document.querySelectorAll("[data-delresult]").forEach(x=>x.onclick=()=>del("results",x.dataset.delresult,"result"));
 document.querySelectorAll("[data-delstaff]").forEach(x=>x.onclick=()=>del("staff",x.dataset.delstaff,"staff"));
 document.querySelectorAll("[data-delnotice]").forEach(x=>x.onclick=()=>del("notices",x.dataset.delnotice,"notice"));
}
function act(a){if(a==="student")studentModal();if(a==="fee")feeModal();if(a==="income"||a==="expense")ledgerModal(a);if(a==="attendanceSave")saveAttendance();if(a==="result")resultModal();if(a==="staff")staffModal();if(a==="salary")salaryModal();if(a==="hostel")hostelModal();if(a==="donor")donorModal();if(a==="notice")noticeModal();if(a==="report")printReport();if(a==="export")exportData();if(a==="import")importData();if(a==="saveSettings")saveSettings();if(a==="reset")reset()}
function modal(title,body,save="Save"){MU.q("#modal").innerHTML=`<div class="backdrop" id="back"><div class="modal"><div class="modalhead"><h3>${title}</h3><button class="iconbtn" id="x"><i class="fa-solid fa-xmark"></i></button></div><div class="modalbody">${body}</div><div class="modalfoot"><button class="btn" id="cancel">Cancel</button><button class="btn primary" id="msave">${save}</button></div></div></div>`;MU.q("#x").onclick=close;MU.q("#cancel").onclick=close;MU.q("#back").onclick=e=>e.target.id==="back"&&close()}
function close(){MU.q("#modal").innerHTML=""}
function select(id,label,opts,val){return `<label>${label}</label><select id="${id}">${opts.map(o=>`<option value="${MU.esc(o)}" ${o===val?"selected":""}>${MU.esc(o)}</option>`).join("")}</select>`}
function studentModal(id){let s=id?S.students.find(x=>x.id===id):{id:MU.id(),name:"",father:"",mother:"",dob:"",gender:"Male",className:"Hifz",roll:"",phone:"",guardian:"",address:"",type:"general",fee:S.settings.fee,admission:MU.today(),status:"active",notes:""};modal(id?"Edit Student":"New Student Admission",`<div class="formgrid">${field("n","Student Name *",s.name)}${field("f","Father's Name",s.father)}${field("m","Mother's Name",s.mother)}${field("dob","Date of Birth",s.dob,"date")}${field("roll","Roll / Student ID",s.roll)}${field("phone","Student Phone",s.phone,"tel")}${field("guard","Guardian Phone",s.guardian,"tel")}${select("gender","Gender",["Male","Female","Other"],s.gender)}${select("cls","Class",["Nurani","Nazera","Hifz","Primary","Other"],s.className)}${select("type","Student Type",["general","orphan"],s.type)}${field("fee","Monthly Fee",s.fee,"number")}${field("adm","Admission Date",s.admission)}${field("address","Address",s.address)}${field("notes","Notes",s.notes)}</div>`,id?"Update":"Admit Student");MU.q("#msave").onclick=async()=>{let x={id,name:MU.q("#n").value.trim(),father:MU.q("#f").value.trim(),mother:MU.q("#m").value.trim(),dob:MU.q("#dob").value,roll:MU.q("#roll").value.trim(),phone:MU.q("#phone").value.trim(),guardian:MU.q("#guard").value.trim(),gender:MU.q("#gender").value,className:MU.q("#cls").value,type:MU.q("#type").value,fee:MU.q("#type").value==="orphan"?0:Number(MU.q("#fee").value||0),admission:MU.q("#adm").value,address:MU.q("#address").value.trim(),notes:MU.q("#notes").value.trim(),status:"active"};if(!x.name)return toast("Student name required",true);let i=S.students.findIndex(z=>z.id===id);i>=0?S.students[i]=x:S.students.push(x);await persist();close();toast(id?"Student updated":"Student admitted")}}
function feeModal(){modal("Collect Fee",`<div class="formgrid">${select("fs","Student",activeStudents().map(x=>`${x.id}|${x.name} — ${x.roll}`),"")}${field("fm","Fee Month",MU.month(),"month")}${field("fe","Expected Fee",S.settings.fee,"number")}${field("fp","Paid Amount","0","number")}${field("fd","Payment Date",MU.today(),"date")}${select("method","Payment Method",["Cash","UPI","Bank","Other"],"Cash")}${field("fn","Note","")}</div><p class="hint">Orphan / এতিম student-এর fee 0 থাকবে।</p>`,"Save & Print");MU.q("#fs").onchange=()=>{let s=S.students.find(x=>x.id===MU.q("#fs").value.split("|")[0]);if(s)MU.q("#fe").value=s.fee};MU.q("#msave").onclick=async()=>{let sid=MU.q("#fs").value.split("|")[0],s=S.students.find(x=>x.id===sid);if(!s)return toast("Select student",true);let expected=Number(MU.q("#fe").value||0),paid=Number(MU.q("#fp").value||0);if(paid<0)return toast("Invalid paid amount",true);let f={id:MU.id(),studentId:s.id,studentName:s.name,roll:s.roll,month:MU.q("#fm").value,date:MU.q("#fd").value,expected,paid,due:Math.max(0,expected-paid),method:MU.q("#method").value,note:MU.q("#fn").value};S.fees.push(f);await persist();close();toast("Fee saved");receipt(f.id)}}
function ledgerModal(k){modal(k==="income"?"Add Income":"Add Expense",`<div class="formgrid">${field("d","Date",MU.today(),"date")}${field("a","Amount","","number")}${field("c","Category",k==="income"?"Donation":"Food")}${field("desc","Description")}${select("pm","Payment Method",["Cash","UPI","Bank","Other"],"Cash")}</div>`);MU.q("#msave").onclick=async()=>{let amount=Number(MU.q("#a").value||0);if(amount<=0)return toast("Enter amount",true);S[k].push({id:MU.id(),date:MU.q("#d").value,amount,category:MU.q("#c").value,description:MU.q("#desc").value,method:MU.q("#pm").value});await persist();close();toast("Saved successfully")}}
function resultModal(){modal("Add Exam Result",`<div class="formgrid">${select("rs","Student",activeStudents().map(x=>`${x.id}|${x.name}`),"")}${field("rex","Exam","Monthly Test")}${field("sub","Subject","Quran")}${field("marks","Marks","","number")}${field("total","Total Marks","100","number")}${field("rd","Date",MU.today(),"date")}</div>`);MU.q("#msave").onclick=async()=>{let sid=MU.q("#rs").value.split("|")[0],s=S.students.find(x=>x.id===sid),m=Number(MU.q("#marks").value),t=Number(MU.q("#total").value||100);if(!s)return toast("Select student",true);let p=m/t*100,g=p>=80?"A+":p>=70?"A":p>=60?"B":p>=50?"C":p>=40?"D":"F";S.results.push({id:MU.id(),date:MU.q("#rd").value,studentId:s.id,studentName:s.name,exam:MU.q("#rex").value,subject:MU.q("#sub").value,marks:m,total:t,grade:g});await persist();close();toast("Result saved")}}
function staffModal(){modal("Add Teacher / Staff",`<div class="formgrid">${field("tn","Name")}${field("tr","Role","Teacher")}${field("tp","Phone")}${field("tj","Join Date",MU.today(),"date")}${field("ts","Monthly Salary","","number")}${select("tstatus","Status",["active","inactive"],"active")}</div>`);MU.q("#msave").onclick=async()=>{if(!MU.q("#tn").value.trim())return toast("Name required",true);S.staff.push({id:MU.id(),name:MU.q("#tn").value,role:MU.q("#tr").value,phone:MU.q("#tp").value,join:MU.q("#tj").value,salary:Number(MU.q("#ts").value||0),status:MU.q("#tstatus").value});await persist();close();toast("Staff added")}}
function salaryModal(){modal("Pay Salary",`<div class="formgrid">${select("ss","Staff",S.staff.filter(x=>x.status!=="inactive").map(x=>`${x.id}|${x.name}`),"")}${field("sm","Month",MU.month(),"month")}${field("sa","Salary","","number")}${field("sp","Paid","","number")}${field("sd","Date",MU.today(),"date")}${select("smet","Method",["Cash","UPI","Bank","Other"],"Cash")}</div>`);MU.q("#msave").onclick=async()=>{let id=MU.q("#ss").value.split("|")[0],s=S.staff.find(x=>x.id===id);if(!s)return toast("Select staff",true);let paid=Number(MU.q("#sp").value||0);S.salary.push({id:MU.id(),staffId:id,staffName:s.name,month:MU.q("#sm").value,salary:Number(MU.q("#sa").value||s.salary),paid,date:MU.q("#sd").value,method:MU.q("#smet").value});await persist();close();toast("Salary saved")}}
function hostelModal(){modal("Food / Hostel Record",`<div class="formgrid">${field("hd","Date",MU.today(),"date")}${field("hc","Category","Food")}${field("hs","Students","0","number")}${field("ha","Amount","","number")}${field("hn","Note")}</div>`);MU.q("#msave").onclick=async()=>{S.hostel.push({id:MU.id(),date:MU.q("#hd").value,category:MU.q("#hc").value,students:Number(MU.q("#hs").value||0),amount:Number(MU.q("#ha").value||0),note:MU.q("#hn").value});await persist();close();toast("Record saved")}}
function donorModal(){modal("Add Donation",`<div class="formgrid">${field("dn","Donor Name")}${field("dp","Phone")}${field("dd","Date",MU.today(),"date")}${field("du","Purpose","General")}${field("da","Amount","","number")}${select("dm","Method",["Cash","UPI","Bank","Other"],"Cash")}</div>`);MU.q("#msave").onclick=async()=>{S.donors.push({id:MU.id(),name:MU.q("#dn").value,phone:MU.q("#dp").value,date:MU.q("#dd").value,purpose:MU.q("#du").value,amount:Number(MU.q("#da").value||0),method:MU.q("#dm").value});await persist();close();toast("Donation saved")}}
function noticeModal(){modal("New Notice",`<div class="form">${field("nt","Title")}${field("nb","Notice", "", "textarea")}${field("nd","Date",MU.today(),"date")}</div>`);MU.q("#msave").onclick=async()=>{S.notices.unshift({id:MU.id(),title:MU.q("#nt").value,body:MU.q("#nb").value,date:MU.q("#nd").value});await persist();close();toast("Notice published")}}
async function saveAttendance(){let date=MU.q("#attDate")?.value||MU.today();document.querySelectorAll(".att").forEach(s=>{let i=S.attendance.findIndex(x=>x.date===date&&x.studentId===s.dataset.att),o={id:i>=0?S.attendance[i].id:MU.id(),date,studentId:s.dataset.att,status:s.value};i>=0?S.attendance[i]=o:S.attendance.push(o)});await persist();toast("Attendance saved")}
async function del(k,id,label){if(!confirm(`Delete this ${label}?`))return;S[k]=S[k].filter(x=>x.id!==id);await persist();toast("Deleted")}
function receipt(id){let f=S.fees.find(x=>x.id===id),s=S.students.find(x=>x.id===f.studentId);let w=open("","_blank");w.document.write(`<html><head><title>Fee Receipt</title><style>body{font-family:Arial;padding:40px;max-width:680px;margin:auto}.c{text-align:center}.row{display:flex;justify-content:space-between;border-bottom:1px solid #ddd;padding:12px}.big{font-size:22px;font-weight:bold}</style></head><body><div class=c><h1>${MU.esc(S.settings.name)}</h1><p>${MU.esc(S.settings.address)} | ${MU.esc(S.settings.phone)}</p><h2>FEE RECEIPT</h2></div><div class=row><span>Receipt No.</span><b>${f.id.slice(0,8).toUpperCase()}</b></div><div class=row><span>Student</span><b>${MU.esc(s?.name||f.studentName)}</b></div><div class=row><span>Roll</span><b>${MU.esc(s?.roll||f.roll)}</b></div><div class=row><span>Month</span><b>${f.month}</b></div><div class=row><span>Expected</span><b>${MU.money(f.expected)}</b></div><div class=row><span>Paid</span><b>${MU.money(f.paid)}</b></div><div class=row><span>Due</span><b>${MU.money(f.due)}</b></div><p style="margin-top:70px">Authorized Signature __________________</p><script>print()</script></body></html>`);w.document.close()}
function printReport(){let c=calc(),w=open("","_blank");w.document.write(`<html><head><title>Monthly Report</title><style>body{font-family:Arial;padding:35px}h1{text-align:center}.g{display:grid;grid-template-columns:1fr 1fr;gap:15px}.b{border:1px solid #ddd;padding:22px}.v{font-size:25px;font-weight:bold;margin-top:8px}</style></head><body><h1>${MU.esc(S.settings.name)}</h1><p style="text-align:center">${MU.month()} Management Report</p><hr><div class=g>${[["Active Students",c.students],["Fee Collection",MU.money(c.paid)],["Other Income",MU.money(c.oi)],["Expense",MU.money(c.eo)],["Total Due",MU.money(c.due)],["Balance",MU.money(c.balance)]].map(x=>`<div class=b>${x[0]}<div class=v>${x[1]}</div></div>`).join("")}</div><script>print()</script></body></html>`);w.document.close()}
function exportData(){MU.download(`dingel-hafizia-backup-${MU.today()}.json`,JSON.stringify(S,null,2))}
function importData(){let i=document.createElement("input");i.type="file";i.accept=".json";i.onchange=()=>{let r=new FileReader();r.onload=async()=>{try{let x=JSON.parse(r.result);if(!x.students)throw 0;S=Object.assign({},defaults,x);await persist();toast("Backup restored")}catch{toast("Invalid backup",true)}};r.readAsText(i.files[0])};i.click()}
function saveSettings(){S.settings.name=MU.q("#sn").value;S.settings.english=MU.q("#se").value;S.settings.address=MU.q("#sa").value;S.settings.phone=MU.q("#sp").value;S.settings.email=MU.q("#sm").value;S.settings.fee=Number(MU.q("#sf").value||0);S.settings.academic=MU.q("#sy").value;S.settings.currency=MU.q("#sc").value;persist();toast("Settings saved")}
function reset(){if(confirm("সব local data মুছে ফেলবেন? আগে backup নিন.")){S=structuredClone(defaults);save();render();toast("Local data reset")}}
MU.q("#menu").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
MU.q("#printBtn").onclick=printReport;MU.q("#searchBtn").onclick=()=>{page="students";render();setTimeout(()=>MU.q("#filter")?.focus(),50)};
MU.q("#themeBtn").onclick=()=>document.body.classList.toggle("dark");
MU.q("#logout").onclick=()=>{if(auth)auth.signOut();toast("Local mode remains available")};
initFirebase();render();
})();